### PR TITLE
Update AA vote procedure

### PR DESCRIPTION
**Pull request by john-light**
Updated to reflect the proposed procedure using an Aragon voting app instead of PGP-signed votes.

### CODE REVIEW

**Comment by luisivan** [comment]
We would deploy a new DAO for this, right?

**Comment by john-light** [comment]
@luisivan that is probably the easiest / least confusing way to do that (vs adding another voting app + token manager to governance.aragonproject.eth)

**Comment by luisivan** [comment]
@john-light makes sense!

**Comment by luisivan** [comment]
Updated [agp-sign](https://github.com/aragon/agp-sign) to comply with this. I'll deploy the DAO soon

**Comment by luisivan** [comment]
DAO has been created and @izqui invited as well. Will post proofs soon https://mainnet.aragon.org/#/associationboard.aragonid.eth

**Pull request merged**
