### PR TITLE
ANSP Engagement Policy

### PR DESCRIPTION
**Pull request by ganeJackS**
ANSP Engagement Policy

Forum Discussion: https://forum.aragon.org/t/draft-agp-for-anv-02-ansp-engagement-policy

### CODE REVIEW

**Comment by john-light** [comment]
@ganeJackS is this proposal finalized?

**Comment by ganeJackS** [comment]
Yes, it is finalized.

**Comment by john-light** [comment]
A technical issue with GitHub is preventing this PR from being merged, but from an AGP Editorial perspective this AGP has been finalized and will be reviewed by the Aragon Association Board of Directors for ANV-02. We will try to resolve this technical issue as soon as possible.

**Comment by ganeJackS** [comment]
Sounds good, thanks for the update

**Comment by luisivan** [comment]
@ganeJackS can you try signing the CLA now?

**Comment by ganeJackS** [comment]
Just signed it, thanks!

**Pull request merged**
