### PR TITLE
AGP Authorship Rewards Program

### PR DESCRIPTION
**Pull request by burrrata**
Proposal to reward AGP authors and contributors in order to incentivize more attention and effort towards Aragon governance.

### CODE REVIEW

**Comment by burrrata** [comment]
@john-light I'd like to make a minor change to this proposal. The `edit` button is no longer available in the GitHub GUI when I view the file. Can I make edits now, or do I have to wait until after the Community Review Period?

**Comment by john-light** [comment]
@burrrata I'm not sure exactly why the file cannot be edited. It seems to be a problem only on your proposal(s). Maybe something to do with this "unknown repository" link shown in this screenshot:

Screenshot_2019-10-09 AGP Authorship Rewards Program by burrrata · Pull Request #100 · aragon AGPs

**Comment by john-light** [comment]
Usually creating a new file directly will cause you to create a new branch / fork automatically. That is the normal workflow I use in the GitHub web UI. It's weird that it is giving you trouble now. I might create a new PR later today for this and the other PRs with a similar issue.

**Comment by john-light** [comment]
The time now is after the published deadline of October 10, 2019 at 16:00 UTC for finalizing proposals and moving them to Stage V, and this proposal has not yet been finalized. Per [AGP-1](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-1.md#stage-iv-community-review), this proposal is considered to be withdrawn and this pull request will now be closed:

> If you do not finalize the proposal and request to move the proposal to Stage V before Stage V is scheduled to begin, AGP Editors will consider the proposal withdrawn and close the pull request when Stage V begins.

**Comment by burrrata** [comment]
New PR for this AGP
- https://github.com/aragon/AGPs/pull/119

**Pull request closed without merging**
