### PR TITLE
AGP-16 PR

### PR DESCRIPTION
**Pull request by lkngtn**
Vote duration changed from 48 Hours (2 Days) to 168 (7 Days). 
Version incremented from 1.0.6 to 1.0.7

### CODE REVIEW

**Comment by john-light** [comment]
@lkngtn while this other PR makes some other changes too, I should note that it also changes the voting duration to one week.

https://github.com/aragon/AGPs/pull/13

Do you want to withdraw yours in favor of #13 or keep it in case voters prefer your reduced scope?

**Comment by lkngtn** [comment]
Hmm, I hadn't realized that the other proposal also changed the duration. I think the change of duration is distinct from the scheduling changes and would actually prefer the scheduling to be unbundled in the other so that there can be two atomic changes.

**Comment by john-light** [comment]
I modified #13 (my proposal) to eliminate the duplication. PR looks good.

**Comment by lkngtn** [comment]
I don't see any issue with swapping out the voting app to reflect the changes in the AGP-1?

**Comment by sohkai** [comment]
@lkngtn It'd mean the old votes would not show up in the new Voting app (unless we upgraded the existing one to a specially modified version).

**Comment by lkngtn** [comment]
The loss of history is a bit of a drag, thanks for pointing that out. (in practice right now there is no way to actually remove the old voting app instances from the UI https://github.com/aragon/aragon/issues/575) so the history would still be visible, but we would have additional voting app instances which would be a drag. 

Creating a custom upgrade for this would be lame. But we could upgrade the voting app to have a change vote duration role. Assuming we did trash the Create permissions role, we could then change the duration of the existing voting app?

On a side note, I think we should try and avoid parameters which can only be set at initiation as much as possible, and instead have a role that allows updating them. The manager of this role can be discarded, essentially making the parameter immutable.

**Comment by sohkai** [comment]
> The manager of this role can be discarded, essentially making the parameter immutable.

We can start going down this path more and more, given the number of headaches we've had trying to adhere to our "strict" nothing-can-change-underneath-you model for the apps.

**Comment by john-light** [comment]
@sohkai this is a bit tangential to this AGP but thought worth noting here for now that if the concern with removing "nothing-can-change-underneath-you" model is one of security, perhaps the client could show the user some visual indication that the app has changed? A couple of ideas come to mind like a "This app has updated since you last used it." banner that the user can close after seeing and "Last updated on [date]" in the corner or somewhere out of the way but easy to find.

**Comment by bingen** [comment]
Some context, as this has been discussed before:
https://github.com/aragon/aragon-apps/pull/98#pullrequestreview-97927732

**Comment by john-light** [comment]
This proposal was rejected by ANT holders: https://mainnet.aragon.org/#/governance.aragonproject.eth/0xcfee4d3078f74197ce77120dbfe6d35f443cab1c

**Pull request closed without merging**
