### PR TITLE
AGP-X: Fund the Mockingbird Incubator & Hub

### PR DESCRIPTION
**Pull request by 0x6431346e**
Forum discussion link: https://forum.aragon.org/t/agp-discussion-fund-the-mockingbird-incubator-hub/1508

TODO:
- [ ] Add PGP sig

### CODE REVIEW

**Comment by 0x6431346e** [comment]
Is this enough to get the AGP into Stage IV? When is the latest I can fill out the organization address?

cc: @john-light @lkngtn

**Comment by john-light** [comment]
@0x6431346e this is enough for the review, you should have a destination for the funds filled out when the proposal is ready to be finalized

**Comment by 0x6431346e** [comment]
Question: is it alright if I significantly change this AGP during this Community Review period?

cc: @john-light

**Comment by john-light** [comment]
@0x6431346e thank you for asking! I think as long as the updated proposal is related to the original proposal it's fine. This is meant to be a review and modification period if modifications are needed. However if the changes are completely unrelated to the original proposal then I would consider that a circumvention of the community review process and would probably not move the proposal to the next stage for this vote.

**Comment by john-light** [comment]
With the approval of [AGP-155](https://github.com/aragon/AGPs/blob/master/AGPs/AGP-155.md) in Aragon Network Vote #6, the AGP process has now been sunset. All open AGP pull requests are now being closed.

Thank you for participating in the AGP process!

**Pull request closed without merging**
