### PR TITLE
Create AragonCoop Finance AGP

### PR DESCRIPTION
**Pull request by sepu85**
this is an AGP for asking a funds transfer to the AragonCoop DAO

### CODE REVIEW

**Comment by sepu85** [comment]
link to forum discussion: https://forum.aragon.org/t/draft-agp-for-anv-2-aragon-cooperative-dao-funding-proposal/783/5

**Comment by john-light** [comment]
Please let the AGP editors know when your proposal has been finalized and you would like to submit it for final review by the Aragon Association. The deadline to finalize and submit your proposal is 16:00 April 11th (note this is in ~50 mins). Proposals not finalized at this time will not be submitted for review.

**Comment by julianbrooks** [comment]
Hey @john-light -- Are we good?

**Comment by sepu85** [comment]
re-confirming the proposal has finalized (after minor updates in the md format)

**Comment by julianbrooks** [comment]
Thanks @sepu85 - appreciated. Nice work

**Comment by julianbrooks** [comment]
Awesome - looks like we're good - many thanks @john-light

**Pull request merged**
